/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as PublicHelpImport } from './routes/_public/help'
import { Route as PrivateDashboardImport } from './routes/_private/dashboard'
import { Route as PrivateChatbotsImport } from './routes/_private/chatbots'
import { Route as PublicHelpIndexImport } from './routes/_public/help.index'
import { Route as PublicHelpPostIdImport } from './routes/_public/help.$postId'
import { Route as PrivateSettingsProfilesImport } from './routes/_private/settings/profiles'
import { Route as PrivateSettingsMailImport } from './routes/_private/settings/mail'
import { Route as PrivateChannelsChannelIdImport } from './routes/_private/channels/$channelId'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PublicHelpRoute = PublicHelpImport.update({
  id: '/_public/help',
  getParentRoute: () => rootRoute,
} as any)

const PrivateDashboardRoute = PrivateDashboardImport.update({
  id: '/_private/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const PrivateChatbotsRoute = PrivateChatbotsImport.update({
  id: '/_private/chatbots',
  getParentRoute: () => rootRoute,
} as any)

const PublicHelpIndexRoute = PublicHelpIndexImport.update({
  path: '/',
  getParentRoute: () => PublicHelpRoute,
} as any)

const PublicHelpPostIdRoute = PublicHelpPostIdImport.update({
  path: '/$postId',
  getParentRoute: () => PublicHelpRoute,
} as any)

const PrivateSettingsProfilesRoute = PrivateSettingsProfilesImport.update({
  id: '/_private/settings/profiles',
  getParentRoute: () => rootRoute,
} as any)

const PrivateSettingsMailRoute = PrivateSettingsMailImport.update({
  id: '/_private/settings/mail',
  getParentRoute: () => rootRoute,
} as any)

const PrivateChannelsChannelIdRoute = PrivateChannelsChannelIdImport.update({
  id: '/_private/channels/$channelId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_private/chatbots': {
      preLoaderRoute: typeof PrivateChatbotsImport
      parentRoute: typeof rootRoute
    }
    '/_private/dashboard': {
      preLoaderRoute: typeof PrivateDashboardImport
      parentRoute: typeof rootRoute
    }
    '/_public/help': {
      preLoaderRoute: typeof PublicHelpImport
      parentRoute: typeof rootRoute
    }
    '/_private/channels/$channelId': {
      preLoaderRoute: typeof PrivateChannelsChannelIdImport
      parentRoute: typeof rootRoute
    }
    '/_private/settings/mail': {
      preLoaderRoute: typeof PrivateSettingsMailImport
      parentRoute: typeof rootRoute
    }
    '/_private/settings/profiles': {
      preLoaderRoute: typeof PrivateSettingsProfilesImport
      parentRoute: typeof rootRoute
    }
    '/_public/help/$postId': {
      preLoaderRoute: typeof PublicHelpPostIdImport
      parentRoute: typeof PublicHelpImport
    }
    '/_public/help/': {
      preLoaderRoute: typeof PublicHelpIndexImport
      parentRoute: typeof PublicHelpImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute,
  PrivateChatbotsRoute,
  PrivateDashboardRoute,
  PublicHelpRoute.addChildren([PublicHelpPostIdRoute, PublicHelpIndexRoute]),
  PrivateChannelsChannelIdRoute,
  PrivateSettingsMailRoute,
  PrivateSettingsProfilesRoute,
])

/* prettier-ignore-end */
