/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivateImport } from './routes/_private'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as PublicHelpImport } from './routes/_public/help'
import { Route as PrivateSettingsImport } from './routes/_private/settings'
import { Route as PrivateDashboardImport } from './routes/_private/dashboard'
import { Route as PrivateChatbotsImport } from './routes/_private/chatbots'
import { Route as AuthSetPasswordImport } from './routes/_auth/set-password'
import { Route as AuthRegisterImport } from './routes/_auth/register'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgot-password'
import { Route as PrivateSettingsIndexImport } from './routes/_private/settings/index'
import { Route as PrivateSettingsThemesImport } from './routes/_private/settings/themes'
import { Route as PrivateSettingsProfilesImport } from './routes/_private/settings/profiles'
import { Route as PrivateSettingsMailImport } from './routes/_private/settings/mail'

// Create/Update Routes

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PublicHelpRoute = PublicHelpImport.update({
  id: '/_public/help',
  getParentRoute: () => rootRoute,
} as any)

const PrivateSettingsRoute = PrivateSettingsImport.update({
  path: '/settings',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateDashboardRoute = PrivateDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateChatbotsRoute = PrivateChatbotsImport.update({
  path: '/chatbots',
  getParentRoute: () => PrivateRoute,
} as any)

const AuthSetPasswordRoute = AuthSetPasswordImport.update({
  path: '/set-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

const PrivateSettingsIndexRoute = PrivateSettingsIndexImport.update({
  path: '/',
  getParentRoute: () => PrivateSettingsRoute,
} as any)

const PrivateSettingsThemesRoute = PrivateSettingsThemesImport.update({
  path: '/themes',
  getParentRoute: () => PrivateSettingsRoute,
} as any)

const PrivateSettingsProfilesRoute = PrivateSettingsProfilesImport.update({
  path: '/profiles',
  getParentRoute: () => PrivateSettingsRoute,
} as any)

const PrivateSettingsMailRoute = PrivateSettingsMailImport.update({
  path: '/mail',
  getParentRoute: () => PrivateSettingsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_private': {
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/_auth/forgot-password': {
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/register': {
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/_auth/set-password': {
      preLoaderRoute: typeof AuthSetPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_private/chatbots': {
      preLoaderRoute: typeof PrivateChatbotsImport
      parentRoute: typeof PrivateImport
    }
    '/_private/dashboard': {
      preLoaderRoute: typeof PrivateDashboardImport
      parentRoute: typeof PrivateImport
    }
    '/_private/settings': {
      preLoaderRoute: typeof PrivateSettingsImport
      parentRoute: typeof PrivateImport
    }
    '/_public/help': {
      preLoaderRoute: typeof PublicHelpImport
      parentRoute: typeof rootRoute
    }
    '/_private/settings/mail': {
      preLoaderRoute: typeof PrivateSettingsMailImport
      parentRoute: typeof PrivateSettingsImport
    }
    '/_private/settings/profiles': {
      preLoaderRoute: typeof PrivateSettingsProfilesImport
      parentRoute: typeof PrivateSettingsImport
    }
    '/_private/settings/themes': {
      preLoaderRoute: typeof PrivateSettingsThemesImport
      parentRoute: typeof PrivateSettingsImport
    }
    '/_private/settings/': {
      preLoaderRoute: typeof PrivateSettingsIndexImport
      parentRoute: typeof PrivateSettingsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthForgotPasswordRoute,
    AuthLoginRoute,
    AuthRegisterRoute,
    AuthSetPasswordRoute,
  ]),
  PrivateRoute.addChildren([
    PrivateChatbotsRoute,
    PrivateDashboardRoute,
    PrivateSettingsRoute.addChildren([
      PrivateSettingsMailRoute,
      PrivateSettingsProfilesRoute,
      PrivateSettingsThemesRoute,
      PrivateSettingsIndexRoute,
    ]),
  ]),
  PublicHelpRoute,
])

/* prettier-ignore-end */
