version: '3.8'

services:
  server:
    container_name: dialogue-bot-server
    image: dialoguebot/server:latest
    restart: 'always'
    ports:
      - '8080:8080'
    networks:
      - backend
  db:
    container_name: dialogue-bot-db
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'dialoguebot'
    volumes:
      [{ type: 'volume', source: 'bot_db', target: '/var/lib/postgresql/data' }]
    restart: 'unless-stopped'
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: 'unless-stopped'
    networks:
      - backend
    volumes: [{ type: 'volume', source: 'redis', target: '/data' }]

networks:
  backend:
    driver: bridge
volumes:
  bot_db:
  pgadmin:
  redis:
