version: '3.8'

services:
   db:
      container_name: dialogue-bot-db
      image: postgres:latest
      ports:
         - '5432:5432'
      environment:
         POSTGRES_PASSWORD: 'postgres'
         POSTGRES_DB: 'dialoguebot'
      volumes:
         [
            {
               type: 'volume',
               source: 'bot_db',
               target: '/var/lib/postgresql/data',
            },
         ]
      restart: 'unless-stopped'
      networks:
         - backend

   pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      ports:
         - '5050:80'
      environment:
         PGADMIN_DEFAULT_EMAIL: 'bot@gmail.com'
         PGADMIN_DEFAULT_PASSWORD: 'admin'
      restart: 'unless-stopped'
      networks:
         - backend
      volumes:
         [{ type: 'volume', source: 'pgadmin', target: '/var/lib/pgadmin' }]

   redis:
      container_name: redis
      image: redis:alpine
      ports:
         - '6379:6379'
      restart: 'unless-stopped'
      networks:
         - backend
      volumes: [{ type: 'volume', source: 'redis', target: '/data' }]

networks:
   backend:
      driver: bridge

volumes:
   bot_db:
   pgadmin:
   redis:
