name:
on:
   push:
      branches:
         - 'main'
jobs:
   build-push:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4
         - name: Login Docker Hub
           uses: docker/login-action@v3
           with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3
           id: buildx
         - name: Build and Push for Server
           uses: docker/build-push-action@v5
           id: docker_build_server
           with:
              context: './server/'
              file: ./server/Dockerfile
              builder: ${{steps.buildx.outputs.name}}
              push: true
              tags: dialoguebot/server:latest
         - name: Build and Push for Client
           uses: docker/build-push-action@v5
           id: docker_build_client
           with:
              context: './client/'
              file: ./client/Dockerfile
              builder: ${{steps.buildx.outputs.name}}
              push: true
              tags: dialoguebot/client:latest
   deploy:
      runs-on: ubuntu-latest
      needs: build-push
      steps:
         - name: executing remote ssh commands using ssh key
           uses: fifsky/ssh-action@master
           with:
              command: |
                 cd /home/ubuntu
                 sudo docker rmi $(sudo docker images --filter "dangling=true" -q --no-trunc)
                 sudo docker compose pull
                 sudo docker compose up -d
              host: ${{ secrets.HOST }}
              user: ${{ secrets.USERNAME }}
              pass: ${{ secrets.PASSWORD }}
