export * from './change-pass'
export * from './forgot-pass'
export * from './general-setting'
export * from './login'
export * from './register'
export * from './set-pass'
export * from './setting-mail'
export * from './variables-setting'
